#!/bin/sh
cd /data & composer install --optimize-autoloader --no-interaction --no-progress

cd /data && source .env
if [[ -z ${APP_KEY} ]]; then
    cd /data && php artisan key:generate
fi

/usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf