services:
  app:
    build:
      context: ./container
      dockerfile: Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: notify_app
    volumes:
      - './src:/data'
    networks:
      - notify
      - mysql
      - mailpit
    depends_on:
      - redis
    ports:
      - 80:80

  redis:
    image: 'redis:alpine'
    container_name: notify_redis
    volumes:
      - './container/redis:/data'
    networks:
      - notify
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      retries: 3
      timeout: 5s

networks:
  notify:
    driver: bridge
  mysql:
    external: true
  mailpit:
    external: true
